name: Reqirement to Test Traceability Check

on:
  pull_request:
    branches: 
      - "main"
      - "Requirements-Analysis" 
    paths:
      - 'docs/**'

jobs:
  verify-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Run Coverage Script
        run: python scripts/req_to_test_check_script.py